import { useState, type ReactNode } from "react";
import { AlertCircle, Check, Copy, Loader2 } from "lucide-react";
import { cn } from "@/lib/utils";
import { timeStamp } from "@/lib/ai";

export function PageHeader({
  eyebrow,
  title,
  sub,
}: {
  eyebrow: string;
  title: string;
  sub: string;
}) {
  return (
    <div className="animate-rise">
      <div className="mono-label font-semibold text-accent">{eyebrow}</div>
      <h1 className="mt-2 font-display text-3xl font-bold sm:text-4xl">{title}</h1>
      <p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted-foreground sm:text-base">
        {sub}
      </p>
    </div>
  );
}

export function DisclaimerBar() {
  return (
    <div className="mt-5 flex items-start gap-2.5 rounded-xl border border-accent-tint-border bg-accent-tint px-4 py-3 text-xs leading-relaxed text-accent-dark">
      <AlertCircle className="mt-0.5 size-4 shrink-0" />
      <span>
        All content here is generated by AI and may contain errors or omissions. Review
        every draft before you send, publish, or act on it, and don't paste confidential or
        sensitive information into these tools.
      </span>
    </div>
  );
}

export function Panel({
  title,
  hint,
  children,
}: {
  title: string;
  hint?: string;
  children: ReactNode;
}) {
  return (
    <div className="rounded-2xl border border-border bg-card p-6 shadow-card">
      <h3 className="font-display text-base font-bold">{title}</h3>
      {hint && <p className="mt-1 text-xs text-muted-foreground">{hint}</p>}
      {children}
    </div>
  );
}

export function Field({ label, children }: { label: string; children: ReactNode }) {
  const id = useId();
  const child = isValidElement(children) ? children : null;
  const isNativeControl =
    child !== null &&
    typeof child.type === "string" &&
    ["input", "textarea", "select"].includes(child.type);

  if (isNativeControl && child) {
    const controlId =
      (child.props as { id?: string }).id ?? `field-${id.replace(/:/g, "")}`;
    return (
      <div className="mt-4">
        <label htmlFor={controlId} className="mb-1.5 block text-xs font-semibold">
          {label}
        </label>
        {cloneElement(child as ReactElement<{ id?: string }>, { id: controlId })}
      </div>
    );
  }

  return (
    <div className="mt-4" role="group" aria-labelledby={`label-${id.replace(/:/g, "")}`}>
      <span
        id={`label-${id.replace(/:/g, "")}`}
        className="mb-1.5 block text-xs font-semibold"
      >
        {label}
      </span>
      {children}
    </div>
  );
}

export const fieldClass =
  "w-full rounded-lg border border-border bg-secondary px-3 py-2.5 text-sm text-foreground placeholder:text-muted-foreground/70 transition-colors focus:border-primary focus:bg-card focus:outline-none focus:ring-2 focus:ring-primary/25";

export function OptionRow<T extends string>({
  options,
  value,
  onChange,
}: {
  options: { value: T; label: string }[];
  value: T;
  onChange: (v: T) => void;
}) {
  return (
    <div className="flex flex-wrap gap-2">
      {options.map((opt) => {
        const active = opt.value === value;
        return (
          <button
            key={opt.value}
            type="button"
            onClick={() => onChange(opt.value)}
            className={cn(
              "min-w-[92px] flex-1 rounded-lg border px-3 py-2.5 text-xs font-semibold transition-all",
              active
                ? "border-primary bg-primary text-primary-foreground shadow-glow"
                : "border-border bg-secondary text-muted-foreground hover:border-primary/40 hover:text-foreground",
            )}
          >
            {opt.label}
          </button>
        );
      })}
    </div>
  );
}

export function PrimaryButton({
  onClick,
  loading,
  label,
  icon: Icon,
}: {
  onClick: () => void;
  loading: boolean;
  label: string;
  icon: React.ComponentType<{ className?: string }>;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      disabled={loading}
      className="mt-6 flex w-full items-center justify-center gap-2 rounded-lg bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground transition-all hover:bg-primary-dark hover:shadow-glow disabled:cursor-not-allowed disabled:bg-muted disabled:text-muted-foreground disabled:shadow-none"
    >
      {loading ? <Loader2 className="size-4 animate-spin" /> : <Icon className="size-4" />}
      {loading ? "Working…" : label}
    </button>
  );
}

export function ErrorNote({ message }: { message?: string }) {
  if (!message) return null;
  return (
    <div className="mt-3 rounded-lg border border-accent-tint-border bg-accent-tint px-3 py-2.5 text-xs text-accent-dark">
      {message}
    </div>
  );
}

export function EmptyState({
  icon: Icon,
  text,
}: {
  icon: React.ComponentType<{ className?: string }>;
  text: string;
}) {
  return (
    <div className="grid-lines flex min-h-[340px] flex-col items-center justify-center rounded-2xl border border-dashed border-border bg-secondary/60 px-6 py-14 text-center">
      <div className="gradient-tint mb-4 flex size-14 items-center justify-center rounded-2xl border border-primary-tint-border">
        <Icon className="size-6 text-primary-dark" />
      </div>
      <p className="max-w-[240px] text-sm text-muted-foreground">{text}</p>
    </div>
  );
}

export function Ticket({
  tag,
  footerNote,
  plainText,
  children,
}: {
  tag: string;
  footerNote?: string;
  plainText: string;
  children: ReactNode;
}) {
  const [copied, setCopied] = useState(false);
  return (
    <div className="animate-rise overflow-hidden rounded-2xl border border-border bg-card shadow-lift">
      <div className="gradient-ink flex items-center justify-between px-5 py-3 font-mono text-[11px] text-ink-foreground">
        <span className="font-semibold text-primary">// {tag}</span>
        <span>{timeStamp()}</span>
      </div>
      <div className="mx-5 border-t border-dashed border-border" />
      <div className="px-6 py-6 text-sm leading-relaxed">{children}</div>
      <div className="flex items-center justify-between gap-3 border-t border-border bg-secondary px-4 py-2.5 font-mono text-[10.5px] text-muted-foreground">
        <span>{footerNote || "AI-generated — please review before use"}</span>
        <button
          type="button"
          onClick={() => {
            navigator.clipboard.writeText(plainText);
            setCopied(true);
            setTimeout(() => setCopied(false), 1500);
          }}
          className="flex items-center gap-1.5 rounded-md border border-border bg-card px-2.5 py-1.5 font-semibold text-foreground transition-colors hover:border-primary hover:text-primary"
        >
          {copied ? <Check className="size-3 text-primary" /> : <Copy className="size-3" />}
          {copied ? "Copied" : "Copy"}
        </button>
      </div>
    </div>
  );
}

export function PriorityBadge({ priority }: { priority: string }) {
  const p = (priority || "medium").toLowerCase();
  return (
    <span
      className={cn(
        "inline-block rounded-full px-2.5 py-0.5 font-mono text-[10.5px] font-semibold",
        p === "high" && "bg-accent-tint text-accent-dark",
        p === "low" && "bg-secondary text-muted-foreground",
        p !== "high" && p !== "low" && "bg-primary-tint text-primary-dark",
      )}
    >
      {p}
    </span>
  );
}

export const twoColClass =
  "mt-7 grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.1fr)]";
